# BLITZR-PRIME — DigitalOcean App Platform Spec
# Deploy version: v1.1.0 — Apr 25 2026 — all 12 audit bugs resolved
name: blitzr-prime
region: blr
services:
  - name: blitzr-backend
    source_dir: /
    build_command: npm install --omit=dev
    run_command: npm start
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: DATABASE_URL
        value: ${blitzr-db.DATABASE_URL}
        scope: RUN_AND_BUILD_TIME
      - key: REDIS_URL
        value: ${blitzr-redis.REDIS_URL}
        scope: RUN_AND_BUILD_TIME
      - key: JWT_SECRET
        value: super_secret_blitzr_campus_key_2024
        scope: RUN_TIME
      - key: SARVAM_API_KEY
        value: sk_2eysz60p_RtAZoqmMEiGXhuW30uhHJY6E
        scope: RUN_TIME
      - key: GOOGLE_CLIENT_ID
        value: 308419908804-tj9rlovie3ddn14nipra2pf78mss3q06.apps.googleusercontent.com
        scope: RUN_TIME
    databases:
      - cluster_name: blitzr-db
        engine: PG
        name: blitzr-db
        production: true
      - cluster_name: blitzr-redis
        engine: REDIS
        name: blitzr-redis
        production: true
